name: mof2
channels:
 - defaults
 - conda-forge
 - https://pose:foldtree@conda.graylab.jhu.edu
dependencies:
 - python>=3.7
 - pyrosetta
 - numpy=1.16.3
 - matplotlib
 - pandas=0.24.2
 - xarray=0.11.3 
 - pytest
 - pytest-faulthandler
 - ipython
 - tqdm
 - yapf
 - pytest-sugar
 - pytest-xdist

